# Generated by Django 5.1.4 on 2026-09-11 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_seed_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-transaction_date', '-created_at']},
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='accounting__transac_211ad8_idx',
            old_name='accounting__transac_1d4d9e_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='accounting__created_b061a5_idx',
            old_name='accounting__created_4b9a84_idx',
        ),
    ]
